graphite:
  image: sitespeedio/graphite:latest
  restart: always
  ports:
    - "8080:80"
    - "2003:2003"
  volumes:
    - $PWD/data/graphite:/opt/graphite/storage/whisper
grafana:
  image: grafana/grafana:3.0.0-beta5
  restart: always
  # command: userdel grafana
  # command: groupadd -g 1000 grafana
  # command: useradd -M -d /var/lib/grafana -u 1000 -g 1000 -s /bin/false grafana
  ports:
    - "3000:3000"
  environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=password
  volumes:
    # - $PWD/data/grafana:/var/lib/grafana:rw
    - /Users/mickey/Developement/sitespeed-docker-compose/data/grafana:/var/lib/grafana